<?php
session_start(); header("Cache-Control: no-store, no-cache, must-revalidate, max-age=0"); header("Pragma: no-cache");
require_once __DIR__ . '/../config/database.php';
if(empty($_SESSION['logged_in'])){header("Location:../login.php");exit;}
if($_SERVER['REQUEST_METHOD']=='POST'){
 $pdo->prepare("INSERT INTO thankyou_messages (payment_id, contributor_id, message, sent_via) VALUES (?,?,?,?)")->execute([$_POST['payment_id'], $_POST['contributor_id'], $_POST['message'], $_POST['via']]);
 header("Location:thankyou.php?msg=sent"); exit;
}
$msgs=$pdo->query("SELECT t.*, c.full_name FROM thankyou_messages t LEFT JOIN contributors c ON t.contributor_id=c.contributor_id ORDER BY t.id DESC")->fetchAll();
$payments=$pdo->query("SELECT p.payment_id, p.amount, c.full_name, c.contributor_id FROM payments p LEFT JOIN contributors c ON p.contributor_id=c.contributor_id WHERE p.status='verified' ORDER BY p.payment_id DESC LIMIT 50")->fetchAll();
?>
<!DOCTYPE html><html><head><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><style>body{background:#f4f7fb}.card{border:none;border-radius:16px}</style></head><body class="p-4">
<div class="container-fluid"><div class="d-flex justify-content-between mb-3"><h4 class="fw-bold">Thank-You Messages</h4><a href="index.php" class="btn btn-dark rounded-pill">Dashboard</a></div>
<div class="row"><div class="col-md-4"><div class="card p-4"><h6>Send Thank You</h6><form method="POST"><select name="payment_id" id="paySel" class="form-control mb-2 rounded-pill" required onchange="setContrib(this)"><option value="">Select Verified Payment</option><?php foreach($payments as $p):?><option value="<?=$p['payment_id']?>" data-cid="<?=$p['contributor_id']?>"><?=$p['full_name']?> - UGX <?=number_format($p['amount'])?></option><?php endforeach;?></select><input type="hidden" name="contributor_id" id="cid"><textarea name="message" class="form-control mb-2 rounded-4" rows="3" required>Dear contributor, Thank you so much for your generous contribution of UGX ... towards Butabika Chaplaincy Construction. May God bless you abundantly! - Board</textarea><select name="via" class="form-control mb-3 rounded-pill"><option value="system">System</option><option value="email">Email</option><option value="sms">SMS</option></select><button class="btn btn-success w-100 rounded-pill">Send Message</button></form><script>function setContrib(s){document.getElementById('cid').value=s.options[s.selectedIndex].getAttribute('data-cid');}</script></div></div>
<div class="col-md-8"><div class="card p-3"><table class="table"><thead><tr><th>To</th><th>Message</th><th>Via</th><th>Date</th></tr></thead><tbody><?php foreach($msgs as $m):?><tr><td><?=$m['full_name']?></td><td><?=$m['message']?></td><td><span class="badge bg-secondary"><?=$m['sent_via']?></span></td><td><small><?=$m['sent_at']?></small></td></tr><?php endforeach;?></tbody></table></div></div></div></div></body></html>